#---
#spring:
#  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#---
#spring:
#  profiles: peer2
#
#server:
#  port: 8762
#
#eureka:
#  instance:
#    hostname: 127.0.0.1
#  client:
##    registerWithEureka: false
##    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
