server:
  port: 8011
spring:
  application:
    name: consumer-user-ribbon-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true